### ISSUE TITLE
Set up local Kubernetes cluster

### ISSUE THREAD

**Issue by disintegrate-Fred** [CSCI-GA-2820-SU24-001/products#51]
**As a** developer  
**I need** to set up a local Kubernetes cluster in my desktop development environment  
**So that** I can deploy and test my microservice locally  

### Details and Assumptions
* Use the `make cluster` command from the Kubernetes lab
* K3S will be used for the local cluster setup

### Acceptance Criteria  
```gherkin
Given I have my development environment set up
When I run the `make cluster` command
Then a local Kubernetes cluster should be created successfully
```

**Comment by SUcy6** [comment]
This is done by enter command line locally. Maybe we can set this story as updating README.md to instruct user how to deploy to Kubernetes (e.g. the steps to set up our service)
