### ISSUE TITLE
Create a database model for Products

### ISSUE THREAD

**Issue by Mihir4921** [CSCI-GA-2820-SU24-001/products#8]
**As a** Product Manager
**I need** a database model for products
**So that** I can efficiently store, manage, and retrieve product information for our e-commerce platform

 ### Details and Assumptions
 * Each product will have attributes such as ID, name, description, price, category, stock quantity, and supplier details.
 * The database should support CRUD (Create, Read, Update, Delete) operations.
 * The database should ensure data integrity and support relationships between products and other entities like categories and suppliers.
 
 ### Acceptance Criteria
 ```gherkin
 Given a selected database
 When a database model is created
 Then a new model with the defined schema is generated that contains all required entities and their relationships.
```

**Comment by SUcy6** [comment]
Should we change the label to technical debt??? The database model may be invisible to users.
